version: "3.7"
services:
  mysql:
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - mysql-data:/var/lib/mysql
  caddy-php:
    build: php
    working_dir: $PWD
    ports:
      - 2015:2015
    volumes:
      - ./:$PWD

      
volumes:
  mysql-data:
